### ISSUE TITLE
Divide up talks

### ISSUE THREAD

**Issue by matthias-stone** [edmontongo/workshopone#1]
- [x] 9:00: 30m 01-Lecture: Introduction (Nick)
- [x] 9:30: 15m 02-Lecture: Basics of Go (Nathan)
- [x] 9:55: 15m 03-Lecture: Types (Brett)
- [x] 10:20: 15m 04-Lecture: Functions & standard library (basics) (James)
- [ ] 10:45: 15m 05-Lecture: Control structures: if, switch, for (while and classic for)
- [x] 11:10: 15m 06-Lecture: Pointers (Matthias)
- [x] 1:00: 15m: 07-Lecture: map (Lukasz)
- [x] 1:25: 15m: 08-Lecture: slices (Nathan)
- [x] 1:50: 15m: 09-Lecture: defined types, structs (Jordan)
- [x] 2:15: 15m: 10-Lecture: Methods (James)
- [x] 2:40: 15m: 11-Lecture: Interfaces (Brett)
- [x] 3:05: 15m: 12-Lecture: Error (Gerrit)
- [x] Introduce Capstone project + `go build` and local environment (Matthias)
- [x] 5:00: 15m: Closing remarks (Nick)

@nathany are you interested in doing a second one?
I don't have Lucasz, but he should get a pick as well.

**Comment by grrtrr** [comment]
@matthias-stone: Error and/or User-defined types, structs, or map would be of interest.

**Comment by nathany** [comment]
@boersn This is a research paper on Go & Swift. You may find some good references for the intro talk. https://github.com/jakerockland/go-vs-swift

I would like a second one. I think it'd be nice to mix up the speakers, so I'd like to leave maps and structs to someone else. Could do errors, depending on what @grrtrr chooses, or basics if nobody else wants it.

Do you think it would be a good idea to use pull requests for the slides and a two thumbs up review? (I assume we will continue editing them for consistency as we go too)

**Comment by grrtrr** [comment]
@nathany Would prefer errors if that is ok with you.

**Comment by stellentus** [comment]
@nathany I haven't learned how to do pull requests yet, but that would be ok with me if the overhead is low.
I think a formal review process is more important for code, since a bug in code pushed to master can cause lots of problems for others, but errors in one person's slides won't mess up anyone else. We should still have a review process because we want high-quality presentations, but I'm not concerned if slides are pushed to master before they're polished.
So either way is fine with me.

**Comment by nathany** [comment]
@stellentus To do a pull request, you just push a branch to this repository, and the GitHub UI will present the option to open a pull request. See [the help](https://help.github.com/articles/about-pull-requests/) for more.

**Comment by nathany** [comment]
Let's decide on who's doing the rest of these talks so we can get the slides ready. Only 3 weeks left!

**Comment by grrtrr** [comment]
@matthias-stone I filled in the 'Error' slot. Am available after 1pm, can fill in one more slot if need to.

**Comment by lukaszroz** [comment]
I added myself for maps in google doc.

**Comment by nathany** [comment]
@grrtrr some error handling resources: https://blog.golang.org/error-handling-and-go https://github.com/RobotsAndPencils/buford/blob/master/pushpackage/pushpackage.go with usage at https://github.com/RobotsAndPencils/buford#website-push.

**Comment by nathany** [comment]
@matthias-stone Do you have an existing outline for control structures? (even if you're not doing that talk)

**Comment by nathany** [comment]
> "since a bug in code pushed to master can cause lots of problems for others"

Since the code is in ordinary Go files, I can setup Travis CI or similar to at least build the code. Feel free to write tests even if they aren't part of the code being demonstrated.

**Comment by torbiak** [comment]
I'm interested in doing Types and Structs.

**Comment by matthias-stone** [comment]
@nathany Sorry, pushed the wrong branch. Updated control structures.

**Comment by nathany** [comment]
thanks. @matthias-stone @lukaszroz are you opening pull requests for your branches?

**Comment by nathany** [comment]
Has everyone had a chance to walk through their slides?

My basics talk was just under 10 and slices was 19! But I did have a lot of questions from the audience, especially on the later.

**Comment by stellentus** [comment]
Functions: 12 minutes without questions
Methods: 7 minutes without questions

**Comment by matthias-stone** [comment]
We gave the workshop 7 months ago. I believe that means the talks were divided.
